[site]
title = "Dr. Cheng Liu"
description = "Researcher in aqueous Zn–MnO<sub>2</sub> batteries and operando characterization."
favicon = "/favicon.svg"
last_updated = "August 27, 2026"

[author]
name = "Dr. Cheng Liu"
title = "Ph.D. Candidate in Materials Science"
institution = "Institute of Materials Science of Barcelona (ICMAB-CSIC)\nUniversitat Autònoma de Barcelona"
avatar = "/bio.jpg"

[social]
email = "liuchzzyy@gmail.com"
location = "Bellaterra, Spain"
location_url = "https://maps.google.com"
location_details = [
  "Department of Solid-State Chemistry (SSC),",
  "Institute of Materials Science of Barcelona (ICMAB-CSIC),",
  "Carrer dels Til·lers sn, 08193 Bellaterra, Spain"
]
google_scholar = "https://scholar.google.com/citations?user=E7pDru4AAAAJ&hl=en"
orcid = "https://orcid.org/0000-0001-8967-1174"
github = "https://github.com/liuchzzyy"
xiaohongshu = "https://www.xiaohongshu.com/user/profile/67154fd1000000001d02113d"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = true
locales = ["zh", "en"]
default_locale = "en"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale (but can be switched still, if you want to disable, set "enable=false")
mode = "auto"
fixed_locale = "en"
# If true, PRISM will remember user's language preference in browser's localStorage
persist = true
# Show a language switcher on the top right corner
switcher = true

[i18n.labels]
zh = "中文"
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Teaching"
type = "page"
target = "teaching"
href = "/teaching"

[[navigation]]
title = "Projects"
type = "page"
target = "services"
href = "/services"

[[navigation]]
title = "News"
type = "page"
target = "news"
href = "/news"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
