[[news]]
date = "2025"
content = "Published \"Unveiling Capacity Limitations of MnO2 in Rechargeable Zn Chemistry\" in *Energy & Environmental Science*."

[[news]]
date = "2023-09"
content = "Received the Best Poster prize at the 74th Annual Meeting of the International Society of Electrochemistry."
