[[news]]
date = "2025"
content = "Published \"Unveiling Capacity Limitations of MnO2 in Rechargeable Zn Chemistry\" in *Energy & Environmental Science*."

[[news]]
date = "2023-09"
content = "Received the Best Poster prize at the 74th Annual Meeting of the International Society of Electrochemistry."

[[news]]
date = "2025-11"
content = "Our work has been accepted by a prestigious journal 🎉"

[[news]]
date = "2025-09"
content = "Starting my PhD at the University of Example"
