type = "list"
title = "新闻动态"
description = "研究动态与公告。"

[[news]]
date = "2025-07"
content = "以第一作者在 *Energy & Environmental Science* 发表 \"Unveiling Capacity Limitations of MnO<sub>2</sub> in Rechargeable Zn Chemistry\"。"

[[news]]
date = "2023-09"
content = "在第 74 届国际电化学学会（ISE）年会上获得最佳海报奖。"
